# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME="asker-exam-debian"

Vagrant.configure("2") do |config|
  config.vm.define NAME do |i|
    i.vm.box = "generic/debian10"
    i.vm.hostname = NAME
    # i.vm.synced_folder "./", "/vagrant"
    i.vm.network "public_network", bridge: ["wlan0"]
    i.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y tree vim
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = NAME
      v.memory = 2048
    end
  end
end
