# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME = "asker-exam-debian"
BOX = "generic/debian10"

Vagrant.configure("2") do |config|
  config.vm.define NAME do |i|
    i.vm.box = BOX
    i.vm.hostname = NAME
    i.vm.synced_folder "./", "/vagrant"
    i.vm.network "public_network", bridge: ["wlan0"]
    i.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y tree vim
      apt install -y ruby irb
    SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = NAME
      v.memory = 2048
    end
  end
end
